name: auto host site
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/*.js'
  push:
    branches:
      - gh-actions
jobs:
  host-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v6
      
      - name: install dependencies
        working-directory: site
        run: npm ci

      - name: start server
        working-directory: site
        run: |
          node app.js &
          echo $! > server.pid

      - name: check process
        working-directory: site
        run: |
          ps -p $(cat server.pid)

      - name: Wait for server
        run: |
          npx wait-on http://localhost:3000/ --timeout 30000

      - name: stop server
        if: always()
        run: kill $(cat server.pid)